### ISSUE TITLE
Incorrect response property name

### ISSUE THREAD

**Issue by sskmy1024y** [t-sweets/pos#32]
https://github.com/t-sweets/pos/blob/b4b2f7e26a7dce21a1c62ba29b69f2c749007c2d/app/controllers/api/auth/registrations_controller.rb#L12

[Wiki](https://github.com/t-sweets/pos/wiki/v1#user-update)だと`data`になってるのに、`product`になってる

**Comment by yuuis** [comment]
ほんとだ
